version: '3.8'

services:
  aws-localstack:
    image: localstack/localstack:0.14.1
    container_name: aws-localstack
    ports:
      - "4566:4566"
    restart: on-failure
    environment:
      - SERVICES=s3,sqs,sns,dynamodb
    volumes:
      - ./init-aws-scripts:/docker-entrypoint-initaws.d
