version: "3.8"

services:
  aws-localstack:
    image: localstack/localstack:0.14.2
    container_name: aws-localstack
    network_mode: bridge
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
    restart: on-failure
    environment:
      - SERVICES=cloudformation,sns,sqs,s3,dynamodb
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
